// theme assets
export const themeAssets = {
  birds: {
    title: "BirdDoku",
    icons: [
      require("../assets/themes/birds/bird_1.png"),
      require("../assets/themes/birds/bird_2.png"),
      require("../assets/themes/birds/bird_3.png"),
      require("../assets/themes/birds/bird_4.png"),
      require("../assets/themes/birds/bird_5.png"),
      require("../assets/themes/birds/bird_6.png"),
      require("../assets/themes/birds/bird_7.png"),
      require("../assets/themes/birds/bird_8.png"),
      require("../assets/themes/birds/bird_9.png"),
    ],
    source: require("../assets/themes/birds/mnt-birds.png"),
    bgSource: require("../assets/themes/birds/MntForest-bg.png"),
    bgSound: require("../assets/themes/birds/forest-guitar-lofi-161108.mp3"),
  },
  fish: {
    title: "FishDoku",
    icons: [
      require("../assets/themes/fish/fish_1.png"),
      require("../assets/themes/fish/fish_2.png"),
      require("../assets/themes/fish/fish_3.png"),
      require("../assets/themes/fish/fish_4.png"),
      require("../assets/themes/fish/fish_5.png"),
      require("../assets/themes/fish/fish_6.png"),
      require("../assets/themes/fish/fish_7.png"),
      require("../assets/themes/fish/fish_8.png"),
      require("../assets/themes/fish/fish_9.png"),
    ],
    source: require("../assets/themes/fish/coral-fish.png"),
    bgSource: require("../assets/themes/fish/ocean-bg.png"),
    bgSound: require("../assets/themes/fish/waves-of-solitude-lofi-beats-281203.mp3"),
  },
  cats: {
    title: "CatDoku",
    icons: [
      require("../assets/themes/cats/cat_1.png"),
      require("../assets/themes/cats/cat_2.png"),
      require("../assets/themes/cats/cat_3.png"),
      require("../assets/themes/cats/cat_4.png"),
      require("../assets/themes/cats/cat_5.png"),
      require("../assets/themes/cats/cat_6.png"),
      require("../assets/themes/cats/cat_7.png"),
      require("../assets/themes/cats/cat_8.png"),
      require("../assets/themes/cats/cat_9.png"),
    ],
    source: require("../assets/themes/cats/cats.png"),
    bgSource: require("../assets/themes/cats/cat-city.png"),
    bgSound: require("../assets/themes/cats/lofi-song-memories-sunbeam-by-lofium-242711.mp3"),
  },
  dogs: {
    title: "DogDoku",
    icons: [
      require("../assets/themes/dogs/dog_1.png"),
      require("../assets/themes/dogs/dog_2.png"),
      require("../assets/themes/dogs/dog_3.png"),
      require("../assets/themes/dogs/dog_4.png"),
      require("../assets/themes/dogs/dog_5.png"),
      require("../assets/themes/dogs/dog_6.png"),
      require("../assets/themes/dogs/dog_7.png"),
      require("../assets/themes/dogs/dog_8.png"),
      require("../assets/themes/dogs/dog_9.png"),
    ],
    source: require("../assets/themes/dogs/dogs.png"),
    bgSource: require("../assets/themes/dogs/dog-park.png"),
    bgSound: require("../assets/themes/dogs/good-morning-upbeat-happy-ukulele-244395.mp3"),
  },
  bugs: {
    title: "BugDoku",
    icons: [
      require("../assets/themes/bugs/bug_1.png"),
      require("../assets/themes/bugs/bug_2.png"),
      require("../assets/themes/bugs/bug_3.png"),
      require("../assets/themes/bugs/bug_4.png"),
      require("../assets/themes/bugs/bug_5.png"),
      require("../assets/themes/bugs/bug_6.png"),
      require("../assets/themes/bugs/bug_7.png"),
      require("../assets/themes/bugs/bug_8.png"),
      require("../assets/themes/bugs/bug_9.png"),
    ],
    source: require("../assets/themes/bugs/bugs.png"),
    bgSource: require("../assets/themes/bugs/leaf-bg.png"),
    bgSound: require("../assets/themes/bugs/whispering-vinyl-loops-lofi-beats-281193.mp3"),
  },
  swamp: {
    title: "SwampDoku",
    icons: [
      require("../assets/themes/swamp/amphibian_1.png"),
      require("../assets/themes/swamp/amphibian_2.png"),
      require("../assets/themes/swamp/amphibian_3.png"),
      require("../assets/themes/swamp/amphibian_4.png"),
      require("../assets/themes/swamp/amphibian_5.png"),
      require("../assets/themes/swamp/amphibian_6.png"),
      require("../assets/themes/swamp/amphibian_7.png"),
      require("../assets/themes/swamp/amphibian_8.png"),
      require("../assets/themes/swamp/amphibian_9.png"),
    ],
    source: require("../assets/themes/swamp/amphibians.png"),
    bgSource: require("../assets/themes/swamp/swamp.png"),
    bgSound: require("../assets/themes/swamp/hip-hoprock-bayou-cheifin-blues-191536.mp3"),
  },
};
